### ISSUE TITLE
Error - Couldn't pass ProxyInitializeEvent to velocityonlinetime

### ISSUE THREAD

**Issue by BartosB13** [Syrent/VelocityOnlineTime#5]
Velocity console on startup

```
[22:24:53 ERROR]: Couldn't pass ProxyInitializeEvent to velocityonlinetime
java.lang.NoClassDefFoundError: net/dv8tion/jda/api/JDABuilder
        at ir.syrent.velocityonlinetime.controller.DiscordController.connect(DiscordController.kt:36) ~[?:?]
        at ir.syrent.velocityonlinetime.controller.DiscordController.<init>(DiscordController.kt:31) ~[?:?]
        at ir.syrent.velocityonlinetime.VelocityOnlineTime.onProxyInitialization(VelocityOnlineTime.java:61) ~[?:?]
        at ir.syrent.velocityonlinetime.Lmbda$29.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity.jar:3.2.0-SNAPSHOT (git-cc74cf85-b238)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.2.0-SNAPSHOT (git-cc74cf85-b238)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.2.0-SNAPSHOT (git-cc74cf85-b238)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.dv8tion.jda.api.JDABuilder
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:87) ~[velocity.jar:3.2.0-SNAPSHOT (git-cc74cf85-b238)]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[velocity.jar:3.2.0-SNAPSHOT (git-cc74cf85-b238)]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 10 more
```

**Comment by NewPixelDev** [comment]
+1
